"""add first_session_completed to user_access_state

Revision ID: 3f906493f317
Revises: b3c4d5e6f7a8
Create Date: 2026-03-18 14:36:26.010806

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f906493f317'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access_states', sa.Column('first_session_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_access_states', 'first_session_completed')
    # ### end Alembic commands ###
