"""add_delivery_error_to_periodic_insight

Revision ID: 4cd7550d1339
Revises: a6dbabfa957b
Create Date: 2026-03-15 11:03:50.321313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4cd7550d1339'
down_revision = 'a6dbabfa957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_insight', sa.Column('delivery_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodic_insight', 'delivery_error')
    # ### end Alembic commands ###
