"""add provider fields to subscription

Revision ID: 50f1ff6548f8
Revises: 82651e1b1ce7
Create Date: 2026-03-18 17:23:04.022054

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50f1ff6548f8'
down_revision = '82651e1b1ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default=sa.text("'telegram_stars'")))
    op.add_column('subscriptions', sa.Column('provider_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'provider_subscription_id')
    op.drop_column('subscriptions', 'provider_type')
    # ### end Alembic commands ###
