"""add apipay fields to purchase_intent

Revision ID: 82651e1b1ce7
Revises: 1e1286f50d2f
Create Date: 2026-03-18 17:12:30.610653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82651e1b1ce7'
down_revision = '1e1286f50d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_intents', sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default=sa.text("'telegram_stars'")))
    op.add_column('purchase_intents', sa.Column('provider_invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('purchase_intents', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.create_index(op.f('ix_purchase_intents_provider_invoice_id'), 'purchase_intents', ['provider_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_intents_provider_invoice_id'), table_name='purchase_intents')
    op.drop_column('purchase_intents', 'phone_number')
    op.drop_column('purchase_intents', 'provider_invoice_id')
    op.drop_column('purchase_intents', 'provider_type')
    # ### end Alembic commands ###
