"""add_periodic_insight_table

Revision ID: a6dbabfa957b
Revises: 0c5fe3b63acb
Create Date: 2026-03-15 10:40:43.238043

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a6dbabfa957b'
down_revision = '0c5fe3b63acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_insight',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('insight_text', sqlmodel.sql.sqltypes.AutoString(length=1500), nullable=False),
    sa.Column('basis_summary_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('generation_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodic_insight_telegram_user_id'), 'periodic_insight', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodic_insight_telegram_user_id'), table_name='periodic_insight')
    op.drop_table('periodic_insight')
    # ### end Alembic commands ###
