"""add_deletion_request_table

Revision ID: ebf7a6e55215
Revises: 4cd7550d1339
Create Date: 2026-03-15 11:50:47.050262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ebf7a6e55215'
down_revision = '4cd7550d1339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_request_telegram_user_id'), 'deletion_request', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deletion_request_telegram_user_id'), table_name='deletion_request')
    op.drop_table('deletion_request')
    # ### end Alembic commands ###
